version: '3.8'

services:
  app:
    image: test-dev:0.0.1
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=production
    networks:
      - minha-rede

networks:
  minha-rede:
    driver: bridge
